services:
  bobapp-back:
    image: ${DOCKER_USERNAME}/bobapp-back:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - bobapp-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8080/api/joke",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  bobapp-front:
    image: ${DOCKER_USERNAME}/bobapp-front:latest
    ports:
      - "80:80"
    depends_on:
      - bobapp-back
    networks:
      - bobapp-network

networks:
  bobapp-network:
    driver: bridge
